# Generated by Django 2.2.6 on 2019-12-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=50, verbose_name='NAME')),
                ('stationId', models.CharField(max_length=50, verbose_name='ID')),
            ],
        ),
    ]
