# Generated by Django 2.2.6 on 2019-12-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='station',
            name='stationName',
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=17, null=True, verbose_name='LAT'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=17, null=True, verbose_name='LNT'),
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='station_name', max_length=50, verbose_name='STATION_NAME'),
        ),
        migrations.AddField(
            model_name='station',
            name='parkingBikeTotCnt',
            field=models.IntegerField(null=True, verbose_name='PARKED_BIKES'),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationId',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
