# Generated by Django 2.2.6 on 2019-12-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191221_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('stationName',)},
        ),
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='stationName',
        ),
    ]
