# Generated by Django 2.2.6 on 2019-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicy_stat', '0002_auto_20191219_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicy_stats',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
