# Generated by Django 2.2.6 on 2019-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicy_stat', '0003_bicy_stats_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stationId', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=17, verbose_name='LAT')),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=17, verbose_name='LNT')),
                ('parkingBikeTotCnt', models.IntegerField(verbose_name='PARKED_BIKES')),
            ],
        ),
    ]
