# Generated by Django 2.2.6 on 2019-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicy_stat', '0004_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, verbose_name='STATION_NAME'),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationId',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
    ]
