# Generated by Django 2.2.6 on 2019-12-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicy_stat', '0005_auto_20191220_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('name',)},
        ),
    ]
