# Generated by Django 2.2.6 on 2019-12-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicy_stat', '0007_auto_20191221_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
